[IMP] portal_event_tickets: fixed error in communications
it-projects-llc/website-addons pull request #11
Opened 2024-11-08 06:14 UTC by azimkhankuat

[IMP] portal_event_tickets: fixed error in communications

2024-11-08 10:21 UTC, em230418 requested changes

2024-11-08 10:21 UTC, em230418 commented on portal_event_tickets/models/event_mail.py
> +            if not rself.event_id.is_done and not rself.event_id.is_finished:
Посмотрел по коду, как определяются is_done и is_finished. Определяются они примерно одинаково и соотвествуют старому состоянию "done". Поэтому оставь is_done, потому-что он определен в website_event

Замены для старого состояния "confirm" тут нету. Надо добавить

2024-11-08 10:22 UTC, em230418 commented
Также исправление надо обозначать как [FIX]. Как тут
https://www.odoo.com/documentation/17.0/contributing/development/git_guidelines.html#tag-and-module-name

2024-11-11 10:09 UTC, azimkhankuat commented on portal_event_tickets/models/event_mail.py
> +            if not rself.event_id.is_done and not rself.event_id.is_finished:
> Замены для старого состояния "confirm" тут нету. Надо добавить

Мне самому добавить поле is_confirmed в "event.event"? Если да, то каким должен быть его compute?

2024-11-12 09:37 UTC, em230418 commented on portal_event_tickets/models/event_mail.py
> +            if not rself.event_id.is_done and not rself.event_id.is_finished:
> Мне самому добавить поле is_confirmed в "event.event"? Если да, то каким должен быть его compute?

Не знаю. Тебе надо выяснить, чему соответствует состояние state = "confirm" из более ранних odoo в odoo 17.0

2024-11-12 10:14 UTC, azimkhankuat commented on portal_event_tickets/models/event_mail.py
> +            if not rself.event_id.is_done and not rself.event_id.is_finished:
> Не знаю. Тебе надо выяснить, чему соответствует состояние state = "confirm" из более ранних odoo в odoo 17.0

Я просто не нашел никакого поля, связанного с confirm. Можешь подсказать, какое поле является его заменой?

2024-11-13 11:26 UTC, em230418 commented on portal_event_tickets/models/event_mail.py
> +            if not rself.event_id.is_done and not rself.event_id.is_finished:
Посмотел коммит, который удаляет этот confirm
https://github.com/odoo/odoo/commit/412ff994f1120457c912aad487265e3de8a9f35a
Походу полноценной замены состояния state = 'confirm' тут нет. 

В таком случае просто оставь упомянутый is_done

2024-11-26 09:48 UTC, em230418 approved these changes

2024-11-26 09:48 UTC, merged