[17.0] [MIG] portal_event_tickets
it-projects-llc/website-addons pull request #9
Opened 2024-10-23 11:16 UTC by azimkhankuat

[17.0] [MIG] portal_event_tickets

2024-10-24 05:31 UTC, em230418 requested changes
Частично проверил

2024-10-24 05:31 UTC, em230418 commented on portal_event_tickets/views/event_registration.xml
>                  >Ticket transferring was started, but haven't finished!</p>
Атрибут убрали, и его замены нету.

2024-10-24 05:31 UTC, em230418 commented on portal_event_tickets/static/src/js/ticket_transfer.tour.esm.js
> +                $("input[type='email']").val("test@test.com");
Если c country_id понятно, ибо поле такого теперь нету. А вот почему phone убрали и поставили test@test.com - не понятно. Это ведь другой тест получится. Нужны пояснения.

2024-10-24 05:31 UTC, em230418 commented on portal_event_tickets/static/src/js/ticket_transfer.tour.esm.js
> +                $("input[type='email']").val("test@test.com");
К слову тут надо не комментировать, а удалять строки.

2024-10-24 05:31 UTC, em230418 commented on portal_event_tickets/static/src/js/ticket_transfer.tour.esm.js
> +                // * job position (optional)
Тут просто удаляем упоминание про country_id и job position.

2024-10-24 05:31 UTC, em230418 commented on portal_event_tickets/tests/common.py
> +
Тут просто удаляем, не комментируем.

2024-10-24 05:31 UTC, em230418 commented on portal_event_tickets/views/portal_templates.xml
> +    </template>
Раздел Ticket выглядит уныло.
![Снимок экрана_2024-10-24_10-11-05](https://github.com/user-attachments/assets/13cc71f9-4768-4d45-8053-718ff51cf814)

Исправить надо также, как когда-то исправлял Affilitates. https://github.com/it-projects-llc/tg-addons/pull/8/files/f53b3d0607dfcacf2a5a33199f1c7f47555f4f03#diff-ac9f3b765e4c8066fdb4848396a07024ae84b647bdff24d03be8e7157594172d

2024-10-24 05:31 UTC, em230418 commented on portal_event_tickets/controllers/main.py
>          partner_vals = request.env["event.registration"]._prepare_partner(registration)
Зачем убираем почту?

2024-10-24 05:31 UTC, em230418 commented on portal_event_tickets/controllers/main.py
>              values.update(
1. country_id точно нужен?
2. Почему нету email?

2024-10-24 05:31 UTC, em230418 commented on portal_event_tickets/controllers/main.py
> +            ._render_qweb_pdf(registration_badge_template, [ticket.id])[0]
Тогда уж request.env['ir.actions.report'], а не request.env.ref(registration_badge_template)

2024-10-28 07:40 UTC, azimkhankuat commented on portal_event_tickets/views/event_registration.xml
>                  >Ticket transferring was started, but haven't finished!</p>
> Атрибут убрали, и его замены нету.

Field 'is_transferring' used in modifier 'invisible' (is_transferring == False) is restricted to the group(s) base.group_no_one.

<xpath expr="//sheet/*[1]" position="before">
                <!-- put it before first element in the form -->
                <p
                    invisible="is_transferring == False"
                    style="color: red"
                >Ticket transferring was started, but haven't finished!</p>
            </xpath>

2024-10-29 11:03 UTC, em230418 commented on portal_event_tickets/views/event_registration.xml
>                  >Ticket transferring was started, but haven't finished!</p>
В таком случае надпимсь "Ticket transferring was started, but haven't finished!" будет постоянно видна.

Само поле is_transferring продублирируй и поставь невидимым рядом с этой надписью.

2024-10-30 10:47 UTC, em230418 commented on portal_event_tickets/views/portal_templates.xml
>          </xpath>
Заверни пожалуйста этот portal_docs_entry в раздел для клиентов. Как тут
https://github.com/odoo/odoo/blob/17.0/addons/account/views/account_portal_templates.xml#L20-L28

2024-10-30 10:58 UTC, em230418 commented on portal_event_tickets/views/portal_templates.xml
> +                            </li>
Эти кнопки надо в одну колонку разместить, как в 14.-

2024-10-30 10:58 UTC, em230418 commented on portal_event_tickets/views/portal_templates.xml
> +                            </li>
![Снимок экрана_2024-10-30_15-57-10](https://github.com/user-attachments/assets/2463de03-bacc-4a29-a910-22f8a193adb7)

2024-10-31 10:32 UTC, em230418 approved these changes

2024-10-31 10:33 UTC, merged